In [1]:
import numpy as np

In [2]:
N_measures_at_each_frequency = 10

In [9]:
normalized_count_rate_pre = []
data_at_one_freq = []
normalized_count_rate_post = []

for a_measure_idx in range(N_measures_at_each_frequency):
    normalized_count_rate_pre.append(np.random.random(20))
    normalized_count_rate_post.append(np.random.random(20)*2)
    data_at_one_freq.append(np.random.random(20)*5)

In [14]:
np.mean(data_at_one_freq)

2.454381136660699

In [15]:
np.mean([normalized_count_rate_pre,normalized_count_rate_post])

0.7820912633232555

In [16]:
np.mean(normalized_count_rate_pre)

0.5108652875217807

In [18]:
(np.mean(normalized_count_rate_post) + np.mean(normalized_count_rate_pre))/2

0.7820912633232556

In [19]:
data_at_one_freq

[array([3.04524319e+00, 9.18904121e-01, 3.78373985e+00, 1.19219004e+00,
        1.87130386e+00, 3.45368225e+00, 8.14302325e-01, 1.54556448e+00,
        1.51546614e+00, 8.51572270e-01, 1.97100282e+00, 4.92054788e-03,
        3.23424371e-01, 4.03466119e+00, 4.96462330e+00, 3.34950822e+00,
        2.53352774e+00, 2.27759447e+00, 3.21752754e+00, 3.76426688e+00]),
 array([3.83165622, 3.67424655, 1.63166988, 1.48603508, 1.31846179,
        4.45022145, 0.96992819, 4.90443534, 2.92829952, 3.69596213,
        4.02879064, 0.37977864, 2.20799904, 4.67720026, 4.9314764 ,
        2.94775025, 3.91014272, 4.57935269, 4.57993403, 1.19444628]),
 array([3.92015331, 3.95021409, 3.65915294, 4.01966197, 4.9320208 ,
        0.24642291, 1.04508792, 0.39306146, 0.612222  , 4.46668129,
        1.90328178, 1.88325482, 4.65843078, 4.76119021, 1.82949757,
        2.67519778, 1.9360491 , 2.40620687, 1.00285143, 1.13020479]),
 array([3.17090134, 3.32973392, 3.42513738, 4.69597104, 2.36857172,
        0.07372528, 1.

In [20]:
np.sum(data_at_one_freq)

490.8762273321398